### ISSUE TITLE
Add users for TKK test

### ISSUE THREAD

**Issue by michielhildebrand** [michielhildebrand/tkk-demo#39]

**Comment by lottebelice** [comment]
The range for this can be:
TKK2015_001
TKK2015_002
TKK2015_003
TKK2015_004
TKK2015_005
TKK2015_006
TKK2015_007
TKK2015_008
TKK2015_009
TKK2015_010
TKK2015_011
TKK2015_012
TKK2015_013
TKK2015_014
TKK2015_015
TKK2015_016
TKK2015_017
TKK2015_018
TKK2015_019
TKK2015_020

If it is really hard to add more later, expand to _025.

And how will this work, as an individual link in PIP, or as a login?
