### ISSUE TITLE
Internationalization of the UI

### ISSUE THREAD

**Issue by michielhildebrand** [michielhildebrand/tkk-demo#41]
Add labels for Dutch (and German?)

**Comment by lottebelice** [comment]
Please note that in the interface as I see it now, "Related artworks" now appears as "Gerelateerde afleveringen", instead of the translation provided. It should be "Gerelateerde fragmenten".

**Comment by michielhildebrand** [comment]
The interface language is translated. I will not translate labels in the content, such as Europeana attributes.

ps. All issues that I close now you will need see in the pip.ia.cwi.nl/culture demo, but in a dedicated version for the test. I will show it at the LinkedTV meeting.
