### ISSUE TITLE
Randomise which dimension is shown at the top

### ISSUE THREAD

**Issue by lottebelice** [michielhildebrand/tkk-demo#42]
When a user goes into explore mode, he/she should randomly see one of the three dimensions at the top, namely:

TKK2015_001	Background
TKK2015_002	Artworks
TKK2015_003	Chapters
TKK2015_004	Background
TKK2015_005	Artworks
TKK2015_006	Chapters
TKK2015_007	Background
TKK2015_008	Artworks
TKK2015_009	Chapters
TKK2015_010	Background
TKK2015_011	Artworks
TKK2015_012	Chapters
TKK2015_013	Background
TKK2015_014	Artworks
TKK2015_015	Chapters
TKK2015_016	Background
TKK2015_017	Artworks
TKK2015_018	Chapters
TKK2015_019	Artworks
TKK2015_020	Chapters

**Comment by michielhildebrand** [comment]
Not for the study as we have the about anyway
