### ISSUE TITLE
Context of chapter in related chapters

### ISSUE THREAD

**Issue by lottebelice** [michielhildebrand/tkk-demo#54]
In the related chapters dimension, you now see "Chapter in episode:" below the preview thumb. However, the actual episode name and date is not shown.

**Comment by michielhildebrand** [comment]
The only thing I get from the editor tool is the title and id of the chapter and the id of the video. Thus, there is not more that I can show directly :(

Of course the application can fetch the content and then display it. I started with this, but it is not yet finished.
