### ISSUE TITLE
New page opens when selecting a hyperlink on an enrichment page

### ISSUE THREAD

**Issue by lottebelice** [michielhildebrand/tkk-demo#56]
When opening the original enrichment page, the user stays in the app, but when you select a hyperlink in an enrichment page, you do leave the app.

**Comment by michielhildebrand** [comment]
I changed to logic for external pages. Clicking links is still an issue. That is the Web! 
Coming back to the app is not so dramatic. 

I close this for now as it will not get better before the user studies.
