### ISSUE TITLE
Navigation from episodes to fragments and back

### ISSUE THREAD

**Issue by lottebelice** [michielhildebrand/tkk-demo#91]
When from the home screen with the episodes, you select to see the fragments of a specific show, you go to the fragment overview. When you however want to return to previous screen, this does not happen when you tap on the 'X'. This results in you landing in all the fragments. This is very confusing, because it is unexpected. Is it possible to provide a 'back' button?

**Comment by lottebelice** [comment]
p.s. I do think it would be nice to (also) show the fragments behind the episode view in a horizontal scroll bar, like we had before. But I know that's a late realisation :). 
![schermafbeelding 2015-02-13 om 14 42 14](https://cloud.githubusercontent.com/assets/6083928/6188162/cbe21a6e-b38e-11e4-8806-fea5ceb65fb7.png)

**Comment by michielhildebrand** [comment]
Can we merge episodes and fragments tabs?

**Comment by michielhildebrand** [comment]
Chapters are shown again in the episodes list.
