### ISSUE TITLE
Filled playlist - why is it there?

### ISSUE THREAD

**Issue by lottebelice** [michielhildebrand/tkk-demo#92]
When I select the hamburger menu from the top left, I see a playlist with fragments. Why is that? It does not seem logical to show it there.

**Comment by michielhildebrand** [comment]
Thuis are the chapters in the video. Where would you expect them?

**Comment by lottebelice** [comment]
I was confused that I also saw them in the screen showing the episode overview. The word playlist just indicates to me something a user has created. But I guess the last episode/chapter you selected servers as input for showing the playlist.
